title: Ruben Oost
email: ruben@oost.io
description: >- 
  My thoughts and projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rubenoost.github.io"
# twitter_username: jekyllrb
github_username:  rubenoost
remote_theme: fongandrew/hydeout
paginate: 10

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
